# --- !Ups

alter table "EVENT" ALTER COLUMN "DATE_OF_EVENT" TYPE TIMESTAMP WITH TIME ZONE;
alter table "EVENT" ALTER COLUMN "REGISTRATION_START_DATE" TYPE TIMESTAMP WITH TIME ZONE;
alter table "EVENT" ALTER COLUMN "REGISTRATION_END_DATE" TYPE TIMESTAMP WITH TIME ZONE;

# --- !Downs
